# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
pod 'BDBOAuth1Manager'
pod 'AFNetworking'
target 'Twitter' do

end

